#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rxvt-unicode
Version  : 9.22
Release  : 7
URL      : http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.22.tar.bz2
Source0  : http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.22.tar.bz2
Summary  : Unicode enabled rxvt-clone terminal emulator (urxvt)
Group    : Development/Tools
License  : GPL-3.0
Requires: rxvt-unicode-bin = %{version}-%{release}
Requires: rxvt-unicode-license = %{version}-%{release}
Requires: rxvt-unicode-man = %{version}-%{release}
BuildRequires : libXft
BuildRequires : libXft-dev

%description
RXVT-UNICODE/URXVT FREQUENTLY ASKED QUESTIONS
Meta, Features & Commandline Issues
My question isn't answered here, can I ask a human?
Before sending me mail, you could go to IRC: "irc.freenode.net", channel
"#rxvt-unicode" has some rxvt-unicode enthusiasts that might be
interested in learning about new and exciting problems (but not FAQs :).

%package bin
Summary: bin components for the rxvt-unicode package.
Group: Binaries
Requires: rxvt-unicode-license = %{version}-%{release}

%description bin
bin components for the rxvt-unicode package.


%package license
Summary: license components for the rxvt-unicode package.
Group: Default

%description license
license components for the rxvt-unicode package.


%package man
Summary: man components for the rxvt-unicode package.
Group: Default

%description man
man components for the rxvt-unicode package.


%prep
%setup -q -n rxvt-unicode-9.22

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1563208061
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --disable-static --enable-256color --disable-perl --enable-xft
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1563208061
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rxvt-unicode
cp COPYING %{buildroot}/usr/share/package-licenses/rxvt-unicode/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/urxvt
/usr/bin/urxvtc
/usr/bin/urxvtd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rxvt-unicode/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/urxvt.1
/usr/share/man/man1/urxvtc.1
/usr/share/man/man1/urxvtd.1
/usr/share/man/man7/urxvt.7
